server:
  port: 8082
spring:
  application:
    name: qa-service
  cloud:
    nacos:
      server-addr: 54.219.180.170:8848
logging:
  level:
    # 将你的FeignClient接口所在的包路径设置为DEBUG
    # 假设 UserClient 在 com.ai.qa.qaservice.feign 包下
    com.ai.qa.qaservice.feign: DEBUG
gemini:
  api:
    key: ${GEMINI_API_KEY:your-api-key-here}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
